cypress_console_defaults:
    commands:
        "doctrine:fixtures:load":
            params: [ "--append" ]

        "rabbitmq:consumer":
            params: [ "-w" ]

        "rabbitmq:anon-consumer":
            params: [ "-w" ]

        "cache:clear":
            params: [ "--no-warmup", "--no-optional-warmers" ]
