old_sound_rabbit_mq:
    connections:
        default:
            host:     %rabbit_host%
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     true

    producers:
#        test:
#            connection:       default
#            exchange_options: {name: 'test', type: direct}

        symfony_log:
            connection: default
            exchange_options: { name: 'symfony_log', type: direct }

    consumers:
#        test:
#            connection:       default
#            exchange_options: {name: 'test', type: direct}
#            queue_options:    {name: 'test'}
#            callback:         cypress.service.consumer

        symfony_log:
            connection:       default
            exchange_options: { name: 'symfony_log', type: direct }
            queue_options:    { name: 'symfony_log' }
            callback:         cypress.service.consumer.log

    anon_consumers:
        rabbit_log:
            connection:       default
            exchange_options: {name: 'log1', type: direct }
            callback:         cypress.service.consumer.log
