old_sound_rabbit_mq:
    connections:
        default:
            host:     %rabbit_host%
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false

    producers:
        log:
            connection: default
            exchange_options: { name: 'log', type: direct }

        test:
            connection:       default
            exchange_options: {name: 'test', type: direct}

    consumers:
        test:
            connection:       default
            exchange_options: {name: 'test', type: direct}
            queue_options:    {name: 'test'}
            callback:         cypress.service.consumer

        log:
            connection:       default
            exchange_options: {name: 'log', type: direct}
            queue_options:    {name: 'log'}
            callback:         cypress.service.consumer.log